version: '3.7'

services:
  backend-server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/triple-project/src
    ports:
      - 3000:3000

  database-server:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'triple-database'
      MYSQL_ROOT_PASSWORD: '1178'
    ports:
      - 3306:3306
